---
title: "Demo for rgantt"
author: "Frank"
date: "2020/8/9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This is a demo for `rgantt` package. You can find the source code of this package [here](https://github.com/frankzhangsyd/rgantt)

```{r}
# devtools::install_github("frankzhangsyd/rgantt")
library(rgantt)
df <- data.frame(
  stringsAsFactors = FALSE,
                id = c("Task 0","Task 1","Task 2",
                       "Task 3","Task 4","Task 5","Task 6"),
             start = c("2020-08-07","2020-08-08",
                       "2020-08-08","2020-08-10","2020-08-14","2020-08-15",
                       "2020-08-17"),
               end = c("2020-08-14","2020-08-11",
                       "2020-08-11","2020-08-13","2020-08-14","2020-08-16",
                       "2020-08-17"),
              name = c("Redesign website",
                       "Write new content","Upgrade systeme","Apply new styles","Review",
                       "Deploy","Go Live!"),
          progress = c(37L, 75L, 75L, 23L, 21L, 61L, 32L),
      dependencies = c(NA,"Task 0","Task 0",
                       "Task 1, Task 2","Task 3",NA,"Task 5")
)
```

I didn't adjust the size intendedly. The below one is the default size of the output. You will need to adjust the size with your duration and your timeframe option (the buttons at the bottom-left)

```{r echo=FALSE}
rgantt(df)
```


